master:
  build: .
  environment:
    JAVA_OPTS: "-Djava.awt.headless=true -Dhudson.footerURL=http://www.u-experten.de/"
  ports:
    - "50000:50000"
    - "80:8080"
  volumes:
    - jenkins_home:/var/jenkins_home
