master:
  build: .
  environment:
    JAVA_OPTS: "-Djava.awt.headless=true -Dhudson.footerURL=http://www.u-experten.de/ -Duser.timezone=Europe/Berlin -Djenkins.slaves.JnlpSlaveAgentProtocol3.enabled=true"
  ports:
    - "50000:50000"
    - "80:8080"
  volumes:
    - jenkins_home:/var/jenkins_home
